[run]
init_cmds = [
	["./lottery"]
]
watch_all = true
watch_dirs = [
	"$WORKDIR/modules"
]
watch_exts = [".go"]
build_delay = 1500
cmds = [
	["go", "install"],
	["go", "build","-o","lottery"],
	["./lottery"]
]